--ACT 11: Table Creation
-- Write SQL to CREATE TABLE products with id, name, and price. Then INSERT 3 rows.

CREATE TABLE products (
	id SERIAL PRIMARY KEY, -- USED SERIAL FOR AUTOMATICALLY GENERATES THE SEQUENCE.
	name VARCHAR(100) NOT NULL, -- USED NOT NULL SO THAT IT WILL NOT INSERT DATA WITHOUT IT.
	price NUMERIC (10,2) NOT NULL CHECK (price >= 0)  -- USED NUMERIC SINCE THE COLUMN IS PRICE, 
	--ALSO ADDED THE CHECK CONSTRAINT SO THAT IT WILL REJECT IF THE INSERTED PRICE IS 0 OR LESS THAN. 
);

INSERT INTO products (name,price) 
VALUES
	('Mouse', 500.00),
	('Web Camera', 1250.00),
	('Keyboard', 3000.00);

SELECT * FROM products;

